### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot-plugin-ssot-infoblox#52]
Documentation:

- README: "the SSoT plugin for Infoblox allows for synchronizing ~source of~ IP network and VLAN data between Infoblox and Nautobot."
- README should document the available options in PLUGINS_CONFIG and what they mean/how to use them
- API documentation is listed as TODO, can probably remove this as there is no API to this plugin
- Probably should remove the "pineapple" GIF, as amusing as it is.

Code:

- Can remove the `api` and `migrations` directories as they're not used in this plugin
- Can remove `tests/test_api.py` and `tests/test_basic.py` as well.

Features:

- For consistency it would be good to also have the plugin create/populate a custom field (a la https://github.com/nautobot/nautobot-plugin-ssot-servicenow/blob/develop/nautobot_ssot_servicenow/signals.py#L28) and use this to report when a given object was last synced (a la https://github.com/nautobot/nautobot-plugin-ssot-servicenow/blob/develop/nautobot_ssot_servicenow/diffsync/adapter_nautobot.py#L212)

CI:

- CI claims that it's running unittest against both Nautobot 1.1.6 and 1.2.4, but the plugin only supports 1.2.0 and later, so 1.1.6 ought to be failing. *It looks like the `poetry.lock` is resulting in Nautobot 1.2.3 being installed for all CI tests, regardless of the Nautobot base docker image being started from* -- see https://github.com/nautobot/nautobot-plugin-ssot-infoblox/runs/4879755615?check_suite_focus=true#step:5:306 for example.

**Comment by dgarros** [comment]
@FragmentedPacket are you good to take this one ?

**Comment by FragmentedPacket** [comment]
Yes I will be addressing this within the next few PRs.
